version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
      - pg_data:/var/lib/postgresql/data
    # Do i need to expose the ports or they build comunication by themself? -- they do communicate with each other.
    #need it to create database manually
    # ports:
    #   - 5432:5432
  redis:
    image: redis
    volumes:
      - redis_data:/data
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4000:80
  rabbitmq:
    image: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
  worker:
    restart: on-failure
    build:
      context: ./dotnet-worker/worker.worker
      dockerfile: Dockerfile.dev
    # volumes:
    # - /app/node_modules
    # - type: bind
    # source: ./worker
    # target: /app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - rabbitmq
      - redis
  node-app:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: on-failure
    # ports:
    #   - 3000:3000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_DATABASE=postgres
      - PG_PASSWORD=admin
      - PG_PORT=5432
      - AMQP_HOST=rabbitmq
    depends_on:
      - rabbitmq
      - redis
    # volumes:
    # - /app/node_modules
    # - type: bind
    #   source: ./backend
    #   target: /app
  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    # ports:
    #   - 5000:5173
    volumes:
      - /app/node_modules
      - ./frontend:/app

volumes:
  pg_data:
  redis_data:
