version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis
    volumes:
      - redis_data:/data
  rabbitmq:
    image: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
  worker:
    restart: on-failure
    build:
      context: ./dotnet-worker/worker.worker
      dockerfile: Dockerfile.dev
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_PASSWORD=admin
    depends_on:
      - rabbitmq
      - redis
  node-app:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: on-failure
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_DATABASE=postgres
      - PG_PASSWORD=admin
      - PG_PORT=5432
      - AMQP_HOST=rabbitmq
      - AMQP_PORT=5672
      - AMQO_USER=admin
      - AMQP_PASSWORD=admin
    depends_on:
      - rabbitmq
      - redis
    ports:
      - "3000:3000"
  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - "4000:5173"

volumes:
  pg_data:
  redis_data:
