version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis_data:/data
  rabbitmq:
    image: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
  worker:
    restart: on-failure
    build:
      context: ./dotnet-worker/worker.worker
      dockerfile: Dockerfile.dev
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_PASSWORD=admin
    depends_on:
      - rabbitmq
      - redis
  node-app:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: on-failure
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_DATABASE=cds_test_office
      - PG_PASSWORD=admin
      - PG_PORT=5432
      - AMQP_HOST=rabbitmq
      - AMQP_PORT=5672
      - AMQO_USER=admin
      - AMQP_PASSWORD=admin
    depends_on:
      - rabbitmq
      - redis
  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - VITE_HOST=react-app
    # dont need this after adding nginx service coz there is no cors issue, they are part of the same network
    # environment:
    #   - FRONTEND_ORIGIN=http://react-app:4000 # Cors issue, what does this do?
    volumes:
      - /app/node_modules
      - ./frontend:/app
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4000:80  
volumes:
  pg_data:
  redis_data:
