# To ensure that both the compose file use the same volume we need them to be in the same drectory
version: '3.8'
services:
  postgres-migrate:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
      - com_data:/var/lib/postgresql/data
  prisma-migrate:
    build:
      context: ./backend
      dockerfile: Dockerfile.migrate
    environment:
      - PG_USER=postgres
      - PG_HOST=postgres-migrate
      - PG_DATABASE=cds_rain
      - PG_PASSWORD=admin
      - PG_PORT=5432
    depends_on:
      - postgres-migrate

volumes:
  com_data:
