version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis_data:/data
  rabbitmq:
    image: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
  node-app-commerce:
    build:
      dockerfile: Dockerfile.dev
    restart: on-failure
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_DATABASE=postgres
      - PG_PASSWORD=admin
      - PG_PORT=5432
      - AMQP_HOST=rabbitmq
      - AMQP_PORT=5672
      - AMQO_USER=admin
      - AMQP_PASSWORD=admin
    depends_on:
      - postgres
      - rabbitmq
      - redis
    ports:
      - "3000:3000"

volumes:
  pg_data:
  redis_data:
