FROM node:alpine

WORKDIR /app

COPY ./package.json ./

RUN npm install

COPY ./ ./

RUN npx prisma generate

# CMD [ "npm", "run", "dev" ]
# CMD [ "npm", "run", "start" ]
CMD ["sh", "-c", "sleep 10 && npm run dev"]
