version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pg_data: