FROM node:alpine

WORKDIR /app

COPY ./package.json ./

RUN npm install

RUN npm prisma migrate deploy
RUN npx prisma generate
RUN Node ./utils/dataSeeder.js

COPY ./ ./

# CMD [ "npm", "run", "dev" ]
CMD [ "npm", "run", "start" ]
