version: '3.8'
services:
  postgres-migrate:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
      - pg_data:/var/lib/postgresql/data
  prisma-migrate:
    build:
      dockerfile: Dockerfile.migrate
    environment:
      - PG_USER=postgres
      - PG_HOST=postgres-migrate
      - PG_DATABASE=cds_test2
      - PG_PASSWORD=admin
      - PG_PORT=5432
    depends_on:
      - postgres-migrate

volumes:
  pg_data:
