version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  redis:
    image: redis:latest

  worker:
    build:
      context: ./worker.worker
      dockerfile: Dockerfile.dev
    restart: on-failure
    depends_on:
      - rabbitmq
      - redis
